services:
  - type: web
    name: marketplace
    env: python
    buildCommand: "./manage.py collectstatic --noinput && ./manage.py migrate"
    startCommand: "gunicorn marketplace.wsgi"
    envVars:
      - key: DEBUG
        value: 'False'
    staticPublishPath: staticfiles
    mediaPublishPath: media