# Generated by Django 5.1 on 2024-08-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_order_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
